version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: user-subscription-db
    environment:
      POSTGRES_DB: user_subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - user-subscription-net

  user-service:
    build: .
    container_name: user-subscription-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-subscription-db:5432/user_subscription_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - user-subscription-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  user-subscription-net:
    driver: bridge